'use strict';
const CARD_TYPE = {
  INVALID: 'INVALID',
  GAME: 'GAME',
  PLAYER: 'PLAYER',
  HERO: 'HERO',
  MINION: 'MINION',
  ABILITY: 'ABILITY',
  ENHANCEMENT: 'ENHANCEMENT',
  WEAPON: 'WEAPON',
  ITEM: 'ITEM',
  TOKEN: 'TOKEN',
  HERO_POWER: 'HERO_POWER',
  SPELL: 'SPELL'
};

export default CARD_TYPE;
