const PLAY_STATE = {
  INVALID: 'INVALID',
  PLAYING: 'PLAYING',
  WINNING: 'WINNING',
  LOSING: 'LOSTING',
  WON: 'WON',
  LOST: 'LOST',
  TIED: 'TIED',
  DISCONNECTED: 'DISCONNECTED',
  CONCEDED: 'CONCEDED',
  QUIT: 'QUIT'
};

export default PLAY_STATE;
