'use strict';

const ZONE = {
  INVALID: 'INVALID',
  CREATED: 'CREATED',
  PLAY: 'PLAY',
  DECK: 'DECK',
  HAND: 'HAND',
  GRAVEYARD: 'GRAVEYARD',
  REMOVEDFROMGAME: 'REMOVEDFROMGAME',
  SETASIDE: 'SETASIDE',
  SECRET: 'SECRET'
};

export default ZONE;
